services:
  matchmaking.service:
    image: ${DOCKER_REGISTRY-}matchmakingservice
    build:
      context: .
      dockerfile: MatchMaking.Service/Dockerfile
    environment:
      KAFKA_BROKERS: kafka-1:9093
    depends_on:
      - kafka
      - redis
  matchmaking.worker:
    image: ${DOCKER_REGISTRY-}matchmakingworker
    deploy:
        replicas: 2
    build:
      context: .
      dockerfile: MatchMaking.Worker/Dockerfile
    environment:
        KAFKA_BROKERS: kafka-1:9093
    depends_on:
      - kafka
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka-1:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SOCKET_TIMEOUT_MS: 30000
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181